### ISSUE TITLE
Native controls not used

### ISSUE THREAD

**Issue by malvese** [mydea/PikadayResponsive#11]
I just tested with the latest Safari on iOS and Chrome on Android, and the native controls don't show up. The Pikaday popup is used instead.
Even on the demo (https://mydea.github.io/PikadayResponsive/) I can't get the native controls on mobile phones.

**Comment by malvese** [comment]
After a bit of research, it seems `Modernizr.touch` returns "undefined". It seems using `Modernizr.touchevents` instead does the trick.

**Comment by mydea** [comment]
Ah, how can I have missed this - thanks for the report. Will try to fix this ASAP, probably tomorrow.

**Comment by mydea** [comment]
Fixed in 0.6.9! Thanks for reporting.
