### ISSUE TITLE
Can't get mobile native controls to work

### ISSUE THREAD

**Issue by cibgraphics** [mydea/PikadayResponsive#13]
I am using the latest bundled version 0.7.0 and I have followed the docs and iOS just can't seem to get the native controls up, just the popup calendar.

```
<input type="date" name="date" id="datepicker">
```

```
var dateObject = pikadayResponsive($('#datepicker'), {
    format: "ddd - MMM D, YYYY"
  });
```

![screen shot 2016-09-01 at 3 24 59 pm](https://cloud.githubusercontent.com/assets/972737/18184959/659ff7fc-7058-11e6-987a-9e5b60dde52b.png)

**Comment by mydea** [comment]
Does the demo work for you on that device? https://mydea.github.io/PikadayResponsive/

I just tried it on an iOS 9 iPad, and it works fine there. Also, can you debug it on Safari? When you connect the iPhone to a Mac, you can inspect its open Safari windows in Mac Safari. Do you see any console messages there?

**Comment by Gerain2k** [comment]
This looks like checkIfNativeDate functions is not triggered you might haven't got Modernizr.

**Comment by mydea** [comment]
I'll close this for now, as this seems to work fine for me. It might very well have been because of Modernizr!
