### ISSUE TITLE
Size of the calendar

### ISSUE THREAD

**Issue by hectorcapulin** [mydea/PikadayResponsive#19]
I have been searching a way to made the calendar smaller, when I use it in a pc it works great, but when I use it in mobile in a fixed div even the column for 'Friday', 'Saturday' and 'Sunday' doesn't appear. There is a way to make it smaller?

**Comment by mydea** [comment]
What exactly do you mean? On a mobile device, it shows the native HTML5 calendar of your OS - we have no influence on how that looks.

**Comment by hectorcapulin** [comment]
Sorry, my bad, I was checking your calendar with the Chrome mobile emulator and shows me the webcalendar, I am checking with my mobile and you're right, thank you.
