### ISSUE TITLE
Same class as the desktop input

### ISSUE THREAD

**Issue by edwinlunando** [mydea/PikadayResponsive#2]
I see that you create another input for the mobile version. i want that mobile input has the same class as the parent input. How can I achieve this?

**Comment by mydea** [comment]
You can do this via the classes option. However, I added this functionality in the latest commit 5d9a9435a37da6da82f4db0ffb55470d9ad6d7a3. Just update to 0.5.2 and you should be good to go!

**Comment by edwinlunando** [comment]
Thanks! It works. :)
