### ISSUE TITLE
NPM installation problem

### ISSUE THREAD

**Issue by Wunsz** [mydea/PikadayResponsive#20]
When using the package in standard NPM-like import:
```js
import PikadayResponsive from 'pikaday-responsive'
```

Following error occurs when building package with webpack.
```
ERROR in ./js/core/editSessionPage.js
Module not found: Error: Cannot resolve module 'pikaday-responsive' in /some/path/to/project/js/core
 @ ./js/core/editSessionPage.js 3:0-877:2
```

While using pure `npm` or `yarn`, user must specify following alias in `webpack.config.js`:
```js
alias: {
    pikaday-responsive: 'pikaday-responsive/src/pikaday-responsive'
}
```

To use it in same way as other node modules that is, like this:
```js
import PikadayResponsive from 'pikaday-responsive'
```

Whereas packages like react does not require any such configuration, and work out of the box.

**Comment by mydea** [comment]
This is because pikaday responsive can also be included without any package manager or similar. I'm not aware of a way to make it work in both scenarios without any further configuration.
