### ISSUE TITLE
Use min and max date for native datepicker

### ISSUE THREAD

**Issue by Gerain2k** [mydea/PikadayResponsive#24]
Hi,
I think it might be useful to have min and max attribute set for native datepicker. I know that it is not fully supported by iOS devices but it does work on Android.
You can do some thing like this:
`$input = $("<input type='date' class='pikaday__invisible' placeholder='" + settings.placeholder + "' min='" 
      + moment(settings.pikadayOptions.minDate , settings.dateformat).format('YYYY-MM-DD') + "' max='" 
      + moment(settings.pikadayOptions.maxDate , settings.dateformat).format('YYYY-MM-DD') + "' " + 
       settings.attributes + " />");`
Or maybe I missed something?
Regards.

**Comment by mydea** [comment]
I'd gladly accept a PR to add this functionality! I'm not actively adding features to this right now, so would depend on someone else adding it. I can also guide you if you need help.

**Comment by Gerain2k** [comment]
Sure thing I will make a PR ether today or tomorrow.

**Comment by Gerain2k** [comment]
Hey I was about to build project with my updates and have a question: Should I upgrade to new version of momentjs and pickaday or leave the old ones?

**Comment by mydea** [comment]
From my view, you can update all dependencies as long as stuff still works afterwards ;)

**Comment by Gerain2k** [comment]
Great. Can you invite me to collaborate so I can make a PR?
