### ISSUE TITLE
Datepicker is disabled on touch?

### ISSUE THREAD

**Issue by woodyc79** [mydea/PikadayResponsive#26]
Hello! 
Unfortunately the date picker is disabled on android touch / chrome touch browsers (also on current version 0.7.x)!
If you try the demo or this one https://mydea.github.io/PikadayResponsive/  with the developer tools (if you enable the device toolbar activated with TOUCH, you have to reload the page), the picker is disabled...

Kind regards,
Christian

**Comment by mydea** [comment]
Yes, this will not work when emulating I guess - but it should work on an actual device.
The code used to check if the native date picker should be used is:

```js
checkIfNativeDate: function() {
      return Modernizr.inputtypes.date && (Modernizr.touchevents && navigator.appVersion.indexOf("Win") === -1);
    },
```

To make it work on Windows computers with touch screens. It does work on my Android phone!

**Comment by woodyc79** [comment]
Unfortunately it is still not working on IOS and Android and emulation (Version 0.7.0)... I think there are many more IOS/Android devices in the wild than windows with touch screens? ;-)

**Comment by mydea** [comment]
Have you actually tried this on a device or just in an emulator? It does work on my android device.

It will not work with the chrome devtools "emulation", as that does not properly emulate the date picker on mobile devices.
