### ISSUE TITLE
Impossible to set a date before 1970

### ISSUE THREAD

**Issue by fclaeys** [mydea/PikadayResponsive#5]
Probably due to the use of moment.unix().

I need to fix this for one of my project, so I work on a PR.

**Comment by mydea** [comment]
Yeah, that is kind of an issue and should definitely be possible. I would welcome a PR.

**Comment by PaulKish** [comment]
+1

**Comment by zacol** [comment]
+1 Any progress?

**Comment by mydea** [comment]
I have just published v0.6.x, which is a complete rewrite of PikadayResponsive. You can update to 0.6.x, where this should be possible. Note however that the public API has changed quite a bit and that you will need adapt your code. I have added a section in the readme with information about how to update. 

If you have any questions or if you notice a bug, feel free to ask.

**Comment by zacol** [comment]
Thank you :)
