### ISSUE TITLE
outputFormat overrides format

### ISSUE THREAD

**Issue by malvese** [mydea/PikadayResponsive#6]
The way I understand the doc, I could use both `format`and `outputFormat` to display a readable date *and* submit a unix timestamp.
But when I try, with options like:
```
    format: "D MMMM YYYY",
    outputFormat: "x",
```
the outputFormat is used for both, and displayed to the user.

Is there a way to achieve what I want?

**Comment by mydea** [comment]
Thanks for the info - the bug should be fixed in 0.6.7.

**Comment by malvese** [comment]
Thank you for the quick fix!
If anyone wants to achieve the same thing in the meantime, here's a quick n'dirty fix:

```
pikadayOptions: {
      onSelect: function() {
        var date = this.getMoment().format('D MMMM YYYY');
        $('#your_targeted_field + .pikaday__display').val(date);
      },
    }
```
It overwrites the date in the display field with one in the format specified with this.getMoment().

**Comment by mydea** [comment]
fyi, 0.6.7 is already released, so you can update right away!

**Comment by malvese** [comment]
:+1:
