### ISSUE TITLE
Update pikaday bower dependency version

### ISSUE THREAD

**Issue by Regaddi** [mydea/PikadayResponsive#8]
Hi @mydea,

dbushell/pikaday has integrated some great commits since the last version 1.4.0, but haven't published a new since then.

I've sent a tweet to @dbushell to publish a new version, but I don't know, when this will happen.

If you don't mind, you can set the bower version currently to the latest master commit, which would be git://github.com/dbushell/Pikaday#c47ec5e0be6e9db07cc7b17ed63385030a8570ff

That'd be helpful, to have some important fixes to pikaday included in my current projects bower dependency chain.

Currently I have to maintain the pikaday master commit "version" separately and bower asks, which version it should use. This is not good for our CI process.

**Comment by Regaddi** [comment]
Alternatively you could switch the dependency to a maintained fork of pikaday, like https://github.com/owenmead/pikaday.

**Comment by mydea** [comment]
I am a bit hesitant about doing this. Right now you can do this by just including the dependencies on their own, like:

```
<script src="bower_components/jquery/dist/jquery.min.js"></script>
<script src="bower_components/momentjs/moment.js"></script>
<script src="bower_components/pikaday/pikaday.js"></script>
<script src="bower_components/pikaday-responsive/dist/pikaday-responsive.js"></script>
```

With this, you can just install pikaday#master and have all the latest features.

**Comment by Regaddi** [comment]
I'm not including separate scripts inside the HTML. There's a concatenated
and minified JS which contains all required JavaScript files that come with
Bower.

My main pain is the prompt on `bower install` that asks for the right
version (the one defined at PikadayResponsive and my "custom one" that
points to the latest master).

Are you going to update your dependency when a new pikaday version is
released?
Am 23.02.2016 5:35 nachm. schrieb "Francesco Novy" <notifications@github.com

**Comment by mydea** [comment]
I definitely want to keep all dependencies up to date, but I prefer to stay on released and tagged versions.

To fix your bower pain, you could just add a resolutions section to your bower.json:

```json
{
  "name": "my project",
  "dependencies": {...},
  "resolutions": {
    "pikaday": "pikaday#master"
  }
}
```

**Comment by olets** [comment]
@Regaddi don't know if you're up on resolving bower to a repo, but I wasn't until just now. Nice clear instructions here http://stackoverflow.com/questions/20311804/how-to-define-a-bower-dependency-to-a-git-repository-with-no-releases-tagged

**Comment by Regaddi** [comment]
Using the resolutions property is indeed the right thing here :) Bower added this property automagically, when I was faced with the resolution prompt.

@olets: This is exactly, what I'm doing right now :)
